/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ActivarRouteImport } from './routes/activar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OlvideContrasenaRouteImport } from './routes/olvide-contrasena'
import { Route as RestablecerRouteImport } from './routes/restablecer'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCredencialesRouteImport } from './routes/_app/credenciales'
import { Route as AppEgresosRouteImport } from './routes/_app/egresos'
import { Route as AppHonorariosRouteImport } from './routes/_app/honorarios'
import { Route as AppPlataformaRouteRouteImport } from './routes/_app/plataforma/route'
import { Route as AppResponsablesRouteImport } from './routes/_app/responsables'
import { Route as AppConfiguracionCategoriasRouteImport } from './routes/_app/configuracion/categorias'
import { Route as AppConfiguracionUsuariosRouteImport } from './routes/_app/configuracion/usuarios'
import { Route as AppPlataformaCatalogosRouteImport } from './routes/_app/plataforma/catalogos'
import { Route as AppPlataformaOrganizacionesRouteImport } from './routes/_app/plataforma/organizaciones'
import { Route as AppPrestadoresIndexRouteImport } from './routes/_app/prestadores/index'
import { Route as AppPrestadoresIdRouteImport } from './routes/_app/prestadores/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivarRoute = ActivarRouteImport.update({
  id: '/activar',
  path: '/activar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OlvideContrasenaRoute = OlvideContrasenaRouteImport.update({
  id: '/olvide-contrasena',
  path: '/olvide-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerRoute = RestablecerRouteImport.update({
  id: '/restablecer',
  path: '/restablecer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCredencialesRoute = AppCredencialesRouteImport.update({
  id: '/credenciales',
  path: '/credenciales',
  getParentRoute: () => AppRoute,
} as any)
const AppEgresosRoute = AppEgresosRouteImport.update({
  id: '/egresos',
  path: '/egresos',
  getParentRoute: () => AppRoute,
} as any)
const AppHonorariosRoute = AppHonorariosRouteImport.update({
  id: '/honorarios',
  path: '/honorarios',
  getParentRoute: () => AppRoute,
} as any)
const AppPlataformaRouteRoute = AppPlataformaRouteRouteImport.update({
  id: '/plataforma',
  path: '/plataforma',
  getParentRoute: () => AppRoute,
} as any)
const AppResponsablesRoute = AppResponsablesRouteImport.update({
  id: '/responsables',
  path: '/responsables',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionCategoriasRoute =
  AppConfiguracionCategoriasRouteImport.update({
    id: '/configuracion/categorias',
    path: '/configuracion/categorias',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracionUsuariosRoute =
  AppConfiguracionUsuariosRouteImport.update({
    id: '/configuracion/usuarios',
    path: '/configuracion/usuarios',
    getParentRoute: () => AppRoute,
  } as any)
const AppPlataformaCatalogosRoute = AppPlataformaCatalogosRouteImport.update({
  id: '/catalogos',
  path: '/catalogos',
  getParentRoute: () => AppPlataformaRouteRoute,
} as any)
const AppPlataformaOrganizacionesRoute =
  AppPlataformaOrganizacionesRouteImport.update({
    id: '/organizaciones',
    path: '/organizaciones',
    getParentRoute: () => AppPlataformaRouteRoute,
  } as any)
const AppPrestadoresIndexRoute = AppPrestadoresIndexRouteImport.update({
  id: '/prestadores/',
  path: '/prestadores/',
  getParentRoute: () => AppRoute,
} as any)
const AppPrestadoresIdRoute = AppPrestadoresIdRouteImport.update({
  id: '/prestadores/$id',
  path: '/prestadores/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/activar': typeof ActivarRoute
  '/login': typeof LoginRoute
  '/olvide-contrasena': typeof OlvideContrasenaRoute
  '/restablecer': typeof RestablecerRoute
  '/plataforma': typeof AppPlataformaRouteRouteWithChildren
  '/credenciales': typeof AppCredencialesRoute
  '/egresos': typeof AppEgresosRoute
  '/honorarios': typeof AppHonorariosRoute
  '/responsables': typeof AppResponsablesRoute
  '/configuracion/categorias': typeof AppConfiguracionCategoriasRoute
  '/configuracion/usuarios': typeof AppConfiguracionUsuariosRoute
  '/plataforma/catalogos': typeof AppPlataformaCatalogosRoute
  '/plataforma/organizaciones': typeof AppPlataformaOrganizacionesRoute
  '/prestadores/$id': typeof AppPrestadoresIdRoute
  '/prestadores/': typeof AppPrestadoresIndexRoute
}
export interface FileRoutesByTo {
  '/activar': typeof ActivarRoute
  '/login': typeof LoginRoute
  '/olvide-contrasena': typeof OlvideContrasenaRoute
  '/restablecer': typeof RestablecerRoute
  '/plataforma': typeof AppPlataformaRouteRouteWithChildren
  '/credenciales': typeof AppCredencialesRoute
  '/egresos': typeof AppEgresosRoute
  '/honorarios': typeof AppHonorariosRoute
  '/responsables': typeof AppResponsablesRoute
  '/': typeof AppIndexRoute
  '/configuracion/categorias': typeof AppConfiguracionCategoriasRoute
  '/configuracion/usuarios': typeof AppConfiguracionUsuariosRoute
  '/plataforma/catalogos': typeof AppPlataformaCatalogosRoute
  '/plataforma/organizaciones': typeof AppPlataformaOrganizacionesRoute
  '/prestadores/$id': typeof AppPrestadoresIdRoute
  '/prestadores': typeof AppPrestadoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/activar': typeof ActivarRoute
  '/login': typeof LoginRoute
  '/olvide-contrasena': typeof OlvideContrasenaRoute
  '/restablecer': typeof RestablecerRoute
  '/_app/plataforma': typeof AppPlataformaRouteRouteWithChildren
  '/_app/credenciales': typeof AppCredencialesRoute
  '/_app/egresos': typeof AppEgresosRoute
  '/_app/honorarios': typeof AppHonorariosRoute
  '/_app/responsables': typeof AppResponsablesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/configuracion/categorias': typeof AppConfiguracionCategoriasRoute
  '/_app/configuracion/usuarios': typeof AppConfiguracionUsuariosRoute
  '/_app/plataforma/catalogos': typeof AppPlataformaCatalogosRoute
  '/_app/plataforma/organizaciones': typeof AppPlataformaOrganizacionesRoute
  '/_app/prestadores/$id': typeof AppPrestadoresIdRoute
  '/_app/prestadores/': typeof AppPrestadoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activar'
    | '/login'
    | '/olvide-contrasena'
    | '/restablecer'
    | '/plataforma'
    | '/credenciales'
    | '/egresos'
    | '/honorarios'
    | '/responsables'
    | '/configuracion/categorias'
    | '/configuracion/usuarios'
    | '/plataforma/catalogos'
    | '/plataforma/organizaciones'
    | '/prestadores/$id'
    | '/prestadores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activar'
    | '/login'
    | '/olvide-contrasena'
    | '/restablecer'
    | '/plataforma'
    | '/credenciales'
    | '/egresos'
    | '/honorarios'
    | '/responsables'
    | '/'
    | '/configuracion/categorias'
    | '/configuracion/usuarios'
    | '/plataforma/catalogos'
    | '/plataforma/organizaciones'
    | '/prestadores/$id'
    | '/prestadores'
  id:
    | '__root__'
    | '/_app'
    | '/activar'
    | '/login'
    | '/olvide-contrasena'
    | '/restablecer'
    | '/_app/plataforma'
    | '/_app/credenciales'
    | '/_app/egresos'
    | '/_app/honorarios'
    | '/_app/responsables'
    | '/_app/'
    | '/_app/configuracion/categorias'
    | '/_app/configuracion/usuarios'
    | '/_app/plataforma/catalogos'
    | '/_app/plataforma/organizaciones'
    | '/_app/prestadores/$id'
    | '/_app/prestadores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ActivarRoute: typeof ActivarRoute
  LoginRoute: typeof LoginRoute
  OlvideContrasenaRoute: typeof OlvideContrasenaRoute
  RestablecerRoute: typeof RestablecerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activar': {
      id: '/activar'
      path: '/activar'
      fullPath: '/activar'
      preLoaderRoute: typeof ActivarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olvide-contrasena': {
      id: '/olvide-contrasena'
      path: '/olvide-contrasena'
      fullPath: '/olvide-contrasena'
      preLoaderRoute: typeof OlvideContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer': {
      id: '/restablecer'
      path: '/restablecer'
      fullPath: '/restablecer'
      preLoaderRoute: typeof RestablecerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credenciales': {
      id: '/_app/credenciales'
      path: '/credenciales'
      fullPath: '/credenciales'
      preLoaderRoute: typeof AppCredencialesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/egresos': {
      id: '/_app/egresos'
      path: '/egresos'
      fullPath: '/egresos'
      preLoaderRoute: typeof AppEgresosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/honorarios': {
      id: '/_app/honorarios'
      path: '/honorarios'
      fullPath: '/honorarios'
      preLoaderRoute: typeof AppHonorariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plataforma': {
      id: '/_app/plataforma'
      path: '/plataforma'
      fullPath: '/plataforma'
      preLoaderRoute: typeof AppPlataformaRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/responsables': {
      id: '/_app/responsables'
      path: '/responsables'
      fullPath: '/responsables'
      preLoaderRoute: typeof AppResponsablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion/categorias': {
      id: '/_app/configuracion/categorias'
      path: '/configuracion/categorias'
      fullPath: '/configuracion/categorias'
      preLoaderRoute: typeof AppConfiguracionCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion/usuarios': {
      id: '/_app/configuracion/usuarios'
      path: '/configuracion/usuarios'
      fullPath: '/configuracion/usuarios'
      preLoaderRoute: typeof AppConfiguracionUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plataforma/catalogos': {
      id: '/_app/plataforma/catalogos'
      path: '/catalogos'
      fullPath: '/plataforma/catalogos'
      preLoaderRoute: typeof AppPlataformaCatalogosRouteImport
      parentRoute: typeof AppPlataformaRouteRoute
    }
    '/_app/plataforma/organizaciones': {
      id: '/_app/plataforma/organizaciones'
      path: '/organizaciones'
      fullPath: '/plataforma/organizaciones'
      preLoaderRoute: typeof AppPlataformaOrganizacionesRouteImport
      parentRoute: typeof AppPlataformaRouteRoute
    }
    '/_app/prestadores/': {
      id: '/_app/prestadores/'
      path: '/prestadores'
      fullPath: '/prestadores/'
      preLoaderRoute: typeof AppPrestadoresIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prestadores/$id': {
      id: '/_app/prestadores/$id'
      path: '/prestadores/$id'
      fullPath: '/prestadores/$id'
      preLoaderRoute: typeof AppPrestadoresIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppPlataformaRouteRouteChildren {
  AppPlataformaCatalogosRoute: typeof AppPlataformaCatalogosRoute
  AppPlataformaOrganizacionesRoute: typeof AppPlataformaOrganizacionesRoute
}

const AppPlataformaRouteRouteChildren: AppPlataformaRouteRouteChildren = {
  AppPlataformaCatalogosRoute: AppPlataformaCatalogosRoute,
  AppPlataformaOrganizacionesRoute: AppPlataformaOrganizacionesRoute,
}

const AppPlataformaRouteRouteWithChildren =
  AppPlataformaRouteRoute._addFileChildren(AppPlataformaRouteRouteChildren)

interface AppRouteChildren {
  AppPlataformaRouteRoute: typeof AppPlataformaRouteRouteWithChildren
  AppCredencialesRoute: typeof AppCredencialesRoute
  AppEgresosRoute: typeof AppEgresosRoute
  AppHonorariosRoute: typeof AppHonorariosRoute
  AppResponsablesRoute: typeof AppResponsablesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConfiguracionCategoriasRoute: typeof AppConfiguracionCategoriasRoute
  AppConfiguracionUsuariosRoute: typeof AppConfiguracionUsuariosRoute
  AppPrestadoresIdRoute: typeof AppPrestadoresIdRoute
  AppPrestadoresIndexRoute: typeof AppPrestadoresIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPlataformaRouteRoute: AppPlataformaRouteRouteWithChildren,
  AppCredencialesRoute: AppCredencialesRoute,
  AppEgresosRoute: AppEgresosRoute,
  AppHonorariosRoute: AppHonorariosRoute,
  AppResponsablesRoute: AppResponsablesRoute,
  AppIndexRoute: AppIndexRoute,
  AppConfiguracionCategoriasRoute: AppConfiguracionCategoriasRoute,
  AppConfiguracionUsuariosRoute: AppConfiguracionUsuariosRoute,
  AppPrestadoresIdRoute: AppPrestadoresIdRoute,
  AppPrestadoresIndexRoute: AppPrestadoresIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ActivarRoute: ActivarRoute,
  LoginRoute: LoginRoute,
  OlvideContrasenaRoute: OlvideContrasenaRoute,
  RestablecerRoute: RestablecerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
