/**
 * Códigos de error estables que viajan en el campo `code` de las respuestas Problem Details.
 * La web los traduce a mensajes en español. Cada feature añade los suyos aquí.
 */
export const ErrorCode = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNPROCESSABLE: 'UNPROCESSABLE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  // F01 — auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  // F02 — organizaciones, catálogos y usuarios
  TAX_ID_TAKEN: 'TAX_ID_TAKEN',
  DUPLICATE_NAME: 'DUPLICATE_NAME',
  SYSTEM_CATEGORY_PROTECTED: 'SYSTEM_CATEGORY_PROTECTED',
  INVALID_CATEGORY_ORDER: 'INVALID_CATEGORY_ORDER',
  ALREADY_MEMBER: 'ALREADY_MEMBER',
  CANNOT_DEACTIVATE_SELF: 'CANNOT_DEACTIVATE_SELF',
  LAST_ADMIN: 'LAST_ADMIN',
  INVITE_NOT_PENDING: 'INVITE_NOT_PENDING',
  // F03 — prestadores y contratos
  INCOMPLETE_BANK_ACCOUNT: 'INCOMPLETE_BANK_ACCOUNT',
  DUPLICATE_DOCUMENT: 'DUPLICATE_DOCUMENT',
  INACTIVE_CATALOG_VALUE: 'INACTIVE_CATALOG_VALUE',
  PROVIDER_HAS_CONTRACTS: 'PROVIDER_HAS_CONTRACTS',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
  CONTRACT_OVERLAP: 'CONTRACT_OVERLAP',
  // F04 — pagos de honorarios
  FEE_PAYMENT_WITHOUT_DAYS: 'FEE_PAYMENT_WITHOUT_DAYS',
  DUPLICATE_WORK_DATE: 'DUPLICATE_WORK_DATE',
  WORK_DATE_OUTSIDE_WEEK: 'WORK_DATE_OUTSIDE_WEEK',
  WORK_DATE_OUTSIDE_CONTRACT: 'WORK_DATE_OUTSIDE_CONTRACT',
  FEE_PAYMENT_ALREADY_EXISTS: 'FEE_PAYMENT_ALREADY_EXISTS',
  FEE_PAYMENT_PERIOD_IMMUTABLE: 'FEE_PAYMENT_PERIOD_IMMUTABLE',
  CONTRACT_HAS_PAYMENTS: 'CONTRACT_HAS_PAYMENTS',
  CONTRACT_DATES_EXCLUDE_PAYMENTS: 'CONTRACT_DATES_EXCLUDE_PAYMENTS',
  CONTRACT_BALANCE_EXCEEDED: 'CONTRACT_BALANCE_EXCEEDED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ProblemFieldError {
  path: string;
  message: string;
}

/** Cuerpo de error según RFC 9457, con `code` y `requestId` propios de AndERP. */
export interface ProblemDetails {
  type: string;
  title: string;
  status: number;
  detail?: string;
  code: string;
  requestId?: string;
  errors?: ProblemFieldError[];
}
